Category.create!(name: "Machinery / Vehicles & Accessories")
Category.create!(name: "Consumer Electronics / Home Appliances")
Category.create!(name: "Green Energy / Solar Panels / Windmills / Batteries")
Category.create!(name: "Apparel / Fashion Accessories / Timepieces,Jewelry,Eyewear")
Category.create!(name: "Beauty & Personal Care / Health & Medical")
Category.create!(name: "Tools & Hardware / Security & Protection / Fabrication Service")
Category.create!(name: "Electrical Equipment & Supplies / Electronic Components,Accessories & Telecommunications")
Category.create!(name: "Packaging & Printing / Office & School Supplies")
Category.create!(name: "Tools & Hardware / Security & Protection / Fabrication Service")
Category.create!(name: "Home & Garden / Furniture")